model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
sandbox_mode = "workspace-write"
approval_policy = "untrusted"

[features]
web_search_request = true
view_image_tool = true

[sandbox_workspace_write]
exclude_tmpdir_env_var = false  # allow $TMPDIR
exclude_slash_tmp = false       # allow /tmp
network_access = true           # opt in to outbound network

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

